# Generated by Django 4.0.5 on 2022-06-06 23:15

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailStory',
            fields=[
                ('by', models.CharField(max_length=200)),
                ('descendants', models.PositiveIntegerField()),
                ('story_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('kids', django_mysql.models.ListCharField(models.PositiveIntegerField(), max_length=408, size=8)),
                ('score', models.PositiveIntegerField()),
                ('time', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_num', models.PositiveIntegerField()),
            ],
        ),
    ]
