# Generated by Django 4.0.5 on 2022-06-07 00:38

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topstories',
            old_name='story_num',
            new_name='num',
        ),
        migrations.AlterField(
            model_name='detailstory',
            name='kids',
            field=django_mysql.models.ListCharField(models.PositiveIntegerField(), max_length=50, size=None),
        ),
        migrations.AlterField(
            model_name='topstories',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
